### ISSUE TITLE
mac. Icons too small.

### ISSUE THREAD

**Issue by gedw99** [emad-elsaid/debugger#1]
this works on mac btw.

I managed to debug a gio app.

Got some hangs. Not sure why yet. But generally this looks like a nice light debugging tool. Great stuff.

I like the simple GUI, but the icons are way too small. For example the "run immediately" checkbox, and also the debugging step through buttons.

**Comment by emad-elsaid** [comment]
thanks @gedw99 Icons can be enlarged quiet easily it takes the fontsize as the icon size, so wrapping the icon function call with `FontEnlarge` will enlarge the icon. 
 I'll do it next time I work on this project.

Also feel free to tinker in it and open a pull request if you feel like it

**Comment by emad-elsaid** [comment]
@gedw99 I enlarged the icons a bit. if you found a way to reproduce the freezing issue I would be grateful

**Comment by gedw99** [comment]
Thanks. Yeah I am playing with it , and will make PR as I see I can help

**Comment by gedw99** [comment]
Oh and about freezing issue, yes I will raise a reproduction issue

**Comment by gedw99** [comment]
I testing the latest main branch again 
using github.com/egonelbre/expgio/cursors as a simple test case.

1. Icons are a good size now.
