### ISSUE TITLE
text.Font error

### ISSUE THREAD

**Issue by zuzmo** [emad-elsaid/debugger#3]
Hi, 
I've tried to go run, but got the next errors:
"# github.com/emad-elsaid/debugger/ui
ui/theme.go:11:22: undefined: text.Cache
ui/theme.go:12:21: undefined: text.Weight
ui/theme.go:21:22: undefined: text.Normal
ui/theme.go:43:19: undefined: text.Cache
ui/theme.go:55:24: undefined: text.Weight
ui/widgets.go:31:20: undefined: text.NewCache
ui/text.go:13:46: undefined: text.Font
ui/text.go:13:94: not enough arguments in call to tl.Layout
	have (layout.Context, <T>, <T>, unit.Sp, string)
	want (layout.Context, *text.Shaper, "gioui.org/font".Font, unit.Sp, string, op.CallOp)
ui/text.go:21:28: undefined: text.Bold
"
I checked, and there is no Cache and Font methods in ui/text.go file.

**Comment by zuzmo** [comment]
The go install works well, so maybe not the latest source is in the repo.

**Comment by emad-elsaid** [comment]
I upgraded the dependencies, it seems there were some refactoring and changes to gioui/text package. this is why latest versions didn't work on your machine I believe.

**Comment by zuzmo** [comment]
It works, thanks!
