### ISSUE TITLE
Project functionality not showing

### ISSUE THREAD

**Issue by gedw99** [emad-elsaid/debugger#4]
The previous version had Projects, Recent Projects and the Debug start stop icon / buttons
At the top of the gui ....

On Mac there don't show up anymore. 

./debugger run .

<img width="1280" alt="Screenshot 2023-06-30 at 17 36 17" src="https://github.com/emad-elsaid/debugger/assets/53147028/742c571a-3ff1-4b41-a0ab-ed81ee5aa410">

Env
```sh
 go version
go version go1.20.4 darwin/amd64
```

**Comment by emad-elsaid** [comment]
* I removed the projects, recent projects window to simplify the code and focus on the debugging screen. the filesystem browser code was a bit much and wasn't the core feature so I removed it in this [commit](https://github.com/emad-elsaid/debugger/commit/a3d86a4777175bedad1cef105bec44a0d24d383a)
* the start/stop buttons appear if the application is running to pause and continue the execution. I see in the screenshot that the application is not running. so the restart button appears at the top
* this is on all systems and not specific to mac

**Comment by gedw99** [comment]
oh damn, i really liked that functionality.

i am totally stuck... 
so how to start and stop and step through ?

**Comment by gedw99** [comment]
i am in Berlin and on telegram of you want to chat...

**Comment by gedw99** [comment]
https://t.me/gedw99

**Comment by gedw99** [comment]
SO i set a break point on main and then pressed restart.

it beachballed for 30 secs and then came back.

then got this. the debugging buttons appearsed ( yeah  ) but are not responding ..

<img width="1280" alt="Screenshot 2023-07-01 at 12 45 01" src="https://github.com/emad-elsaid/debugger/assets/53147028/5d5c761e-8419-493a-936c-0ff90ee84ca6">

```
apple@x-MacBook-Pro-2 debugger % debugger run .
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1300.0.42.3
 for x86_64.
Got a connection, launched process /Users/apple/workspace/go/src/github.com/_jumk/debugger/debug (pid = 64907).
2023/07/01 12:38:56 debugger needs a command: `run` or `test`
Exiting.
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1300.0.42.3
 for x86_64.
Got a connection, launched process /Users/apple/workspace/go/src/github.com/_jumk/debugger/debug (pid = 64911).
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1300.0.42.3
 for x86_64.
Got a connection, launched process /Users/apple/workspace/go/src/github.com/_jumk/debugger/debug (pid = 64928).
^C%                                                                                                                                                                                  apple@x-MacBook-Pro-2 debugger % debugger run . 
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1300.0.42.3
 for x86_64.
Got a connection, launched process /Users/apple/workspace/go/src/github.com/_jumk/debugger/debug (pid = 64979).
2023/07/01 12:39:44 debugger needs a command: `run` or `test`
Exiting.
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1300.0.42.3
 for x86_64.
Got a connection, launched process /Users/apple/workspace/go/src/github.com/_jumk/debugger/debug (pid = 64983).
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1300.0.42.3
 for x86_64.
Got a connection, launched process /Users/apple/workspace/go/src/github.com/_jumk/debugger/debug (pid = 65062).
^C^C^C2023/07/01 12:44:29 ERR write tcp 127.0.0.1:63125->127.0.0.1:63126: write: broken pipe
2023/07/01 12:44:30 ERR write tcp 127.0.0.1:63125->127.0.0.1:63126: write: broken pipe
2023/07/01 12:44:41 ERR write tcp 127.0.0.1:63125->127.0.0.1:63126: write: broken pipe
2023/07/01 12:44:42 ERR write tcp 127.0.0.1:63125->127.0.0.1:63126: write: broken pipe
2023/07/01 12:44:43 ERR write tcp 127.0.0.1:63125->127.0.0.1:63126: write: broken pipe
2023/07/01 12:44:43 ERR write tcp 127.0.0.1:63125->127.0.0.1:63126: write: broken pipe
2023/07/01 12:44:43 ERR could not find statement at /Users/apple/workspace/go/src/github.com/_jumk/debugger/main.go:23, please use a line with a statement
2023/07/01 12:44:44 ERR could not find statement at /Users/apple/workspace/go/src/github.com/_jumk/debugger/main.go:23, please use a line with a statement
2023/07/01 12:44:44 ERR write tcp 127.0.0.1:63125->127.0.0.1:63126: write: broken pipe
2023/07/01 12:44:44 ERR write tcp 127.0.0.1:63125->127.0.0.1:63126: write: broken pipe
2023/07/01 12:44:45 ERR write tcp 127.0.0.1:63125->127.0.0.1:63126: write: broken pipe
2023/07/01 12:44:45 ERR write tcp 127.0.0.1:63125->127.0.0.1:63126: write: broken pipe
2023/07/01 12:44:46 ERR write tcp 127.0.0.1:63125->127.0.0.1:63126: write: broken pipe
2023/07/01 12:44:46 ERR write tcp 127.0.0.1:63125->127.0.0.1:63126: write: broken pipe
```

**Comment by gedw99** [comment]
I then tried "using a line with a statement"

but again the gui stalled. I had to do ctr-c on the terminal to get it  the gui to become alive.

but then "broken piped" and not ability to set debug points in  the gui.

```sh
debugger run . 
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1300.0.42.3
 for x86_64.
Got a connection, launched process /Users/apple/workspace/go/src/github.com/_jumk/debugger/debug (pid = 65177).
2023/07/01 12:47:26 debugger needs a command: `run` or `test`
Exiting.
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1300.0.42.3
 for x86_64.
Got a connection, launched process /Users/apple/workspace/go/src/github.com/_jumk/debugger/debug (pid = 65182).
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1300.0.42.3
 for x86_64.
Got a connection, launched process /Users/apple/workspace/go/src/github.com/_jumk/debugger/debug (pid = 65198).
^C2023/07/01 12:48:53 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:48:54 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:48:56 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:48:56 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:48:57 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:48:57 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:48:59 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:48:59 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:48:59 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:48:59 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:48:59 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:49:00 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:49:00 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:49:00 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:49:01 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:49:01 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:49:01 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:49:01 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:49:39 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:49:39 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:49:40 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
2023/07/01 12:49:41 ERR write tcp 127.0.0.1:63157->127.0.0.1:63158: write: broken pipe
```

**Comment by gedw99** [comment]
I can make a video  if you want..

**Comment by emad-elsaid** [comment]
yeah maybe if a video and a test repo to regenerate the issue on my machine

**Comment by gedw99** [comment]
On will do it on Monday. 

Btw I really like the way the cli args are designed !! It makes it really flexible for real world debugging. Good job

**Comment by gedw99** [comment]
Hey @emad-elsaid 

I had alot of trouble making a video demo , but here it is: https://youtu.be/bJMJq20KZ9o

the trouble was that it was very slow to attached to the debugger after selecting a break point.
and then the app i was debugging seems to become "detached" from the OS, in that it would disappear from the OS task manager, etc 

I don't know if this is a Mac specific thing as i dont have another OS to try this on either.

**Comment by emad-elsaid** [comment]
I tried to replicate the issue but I'm not sure if it's an issue that happens on your machine or a misunderstanding of what is happening. so I'l explain what I tried in this video

https://github.com/emad-elsaid/debugger/assets/54403/7fe818d0-a93f-4988-b6d9-b2d8f26d2c49

* I rand `debugger run ./cmd/xlog/xlog.go -- --index Home --source ~/code/emad-elsaid.github.io/` this runs `debugger` to debug `xlog` from `./cmd/xlog/xlog.go` with the source files from my blog directory. similar to what you did.
* now `xlog` server already started and waiting for connections. so when I go to the browser and visit `localhost:3000` it shows the home page
* now here is an issue: I go and add a breakpoint to the line inside `main` and it just selects it. it should show a red mark on the line number. (this is a bug, the breakpoint is added but it doesn't show up. I will fix that). 
* now I restart the program with the refresh button at the top. this restarts xlog and the debugger stops at the line we have a breakpoint at. this is correct. and this means the server is not running. so when I refresh the browser it can't find the server.
* when I press continue the execute continues and the browser shows the home page again.

from you video I'm not sure about the issue. but I see two differences to what I do: 
- when you pressed the stop button this means the debugged program is terminated so it's correct that it doesn't apprear in the activity monitor
- I noticed that in the activity monitor there is `(not responding)` in front of `debugger` and the video shows the GUI is hidden. (I need more information about that, some times I debug `debugger` with itself. it can help also to use some other debugger interface to debug `debugger` to understand where does it freeze. 
- the thing is on my machine this doesn't happen. so it's a bit hard to fix the issue

**Comment by gedw99** [comment]
Ok so the red dot not showing is a bug .

m the other thing was the program I was debugging disappearing. My hunch is that it might be a MAC thing. What OS did you use btw ?

**Comment by emad-elsaid** [comment]
I'm using a Linux machine.
> Operating System: Arch Linux
          Kernel: Linux 6.4.1-arch2-1
    Architecture: x86-64

UI is X11, i3, compositor picom

**Comment by gedw99** [comment]
I will try again to debug xlog .

If you have a Mac you try it too.

I know it sounds crazy that xlog disappeared from the OS task manage but it did :)

**Comment by gedw99** [comment]
I am closing this, and make a new issue where i think i have found the problem.
